const sampleReviews = {
	status: "success",
	result: [
		{
			id: 1001,
			type: "guest-to-host",
			status: "published",
			rating: 9,
			publicReview:
				"Amazing stay! The property was spotless and exactly as described. Great location near restaurants and shops.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 9 },
				{ category: "check-in", rating: 9 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 9 },
			],
			submittedAt: "2024-10-10 14:23:11",
			guestName: "Emma Thompson",
			listingName: "Skyline Penthouse - Downtown Luxury",
		},
		{
			id: 1002,
			type: "host-to-guest",
			status: "published",
			rating: null,
			publicReview:
				"Emma was a wonderful guest! Left the place clean and followed all house rules.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "respect_house_rules", rating: 10 },
			],
			submittedAt: "2024-10-11 09:15:22",
			guestName: "Emma Thompson",
			listingName: "Skyline Penthouse - Downtown Luxury",
		},
		{
			id: 1003,
			type: "guest-to-host",
			status: "published",
			rating: 7,
			publicReview:
				"Good location but the apartment could use some updates. WiFi was a bit slow.",
			reviewCategory: [
				{ category: "cleanliness", rating: 8 },
				{ category: "communication", rating: 9 },
				{ category: "check-in", rating: 8 },
				{ category: "accuracy", rating: 6 },
				{ category: "location", rating: 9 },
			],
			submittedAt: "2024-09-28 18:45:33",
			guestName: "Marcus Johnson",
			listingName: "Cozy Studio - Arts District",
		},
		{
			id: 1004,
			type: "guest-to-host",
			status: "published",
			rating: 10,
			publicReview:
				"Absolutely perfect! The rooftop terrace was stunning. Host was super responsive and helpful.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 10 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-10-05 11:30:45",
			guestName: "Sofia Rodriguez",
			listingName: "Sunset View Apartment - Marina Bay",
		},
		{
			id: 1005,
			type: "guest-to-host",
			status: "published",
			rating: 5,
			publicReview:
				"The place was okay but not as clean as expected. Location was convenient though.",
			reviewCategory: [
				{ category: "cleanliness", rating: 4 },
				{ category: "communication", rating: 7 },
				{ category: "check-in", rating: 6 },
				{ category: "accuracy", rating: 5 },
				{ category: "location", rating: 8 },
			],
			submittedAt: "2024-09-15 20:12:18",
			guestName: "David Chen",
			listingName: "Modern Loft - Tech Quarter",
		},
		{
			id: 1006,
			type: "host-to-guest",
			status: "published",
			rating: null,
			publicReview: "Great guests! Would happily host again.",
			reviewCategory: [
				{ category: "cleanliness", rating: 9 },
				{ category: "communication", rating: 10 },
				{ category: "respect_house_rules", rating: 9 },
			],
			submittedAt: "2024-09-16 10:05:44",
			guestName: "David Chen",
			listingName: "Modern Loft - Tech Quarter",
		},
		{
			id: 1007,
			type: "guest-to-host",
			status: "published",
			rating: 8,
			publicReview:
				"Lovely apartment with great amenities. The building gym was a nice bonus!",
			reviewCategory: [
				{ category: "cleanliness", rating: 9 },
				{ category: "communication", rating: 8 },
				{ category: "check-in", rating: 8 },
				{ category: "accuracy", rating: 8 },
				{ category: "location", rating: 7 },
			],
			submittedAt: "2024-10-02 16:20:55",
			guestName: "Aisha Patel",
			listingName: "Garden View Suite - Riverside",
		},
		{
			id: 1008,
			type: "guest-to-host",
			status: "published",
			rating: 9,
			publicReview:
				"Perfect for our family vacation. Kids loved the pool! Host provided great local recommendations.",
			reviewCategory: [
				{ category: "cleanliness", rating: 9 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 9 },
				{ category: "accuracy", rating: 9 },
				{ category: "location", rating: 8 },
			],
			submittedAt: "2024-09-22 13:40:27",
			guestName: "Robert Williams",
			listingName: "Beach House - Coastal Paradise",
		},
		{
			id: 1009,
			type: "guest-to-host",
			status: "submitted",
			rating: 6,
			publicReview:
				"Check-in process was confusing. The apartment itself was decent but needs better instructions.",
			reviewCategory: [
				{ category: "cleanliness", rating: 7 },
				{ category: "communication", rating: 5 },
				{ category: "check-in", rating: 4 },
				{ category: "accuracy", rating: 7 },
				{ category: "location", rating: 8 },
			],
			submittedAt: "2024-10-12 19:55:09",
			guestName: "Lisa Anderson",
			listingName: "City Center Flat - Business District",
		},
		{
			id: 1010,
			type: "guest-to-host",
			status: "published",
			rating: 10,
			publicReview:
				"Exceptional! Best Airbnb experience ever. The attention to detail was outstanding.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 10 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-09-08 12:10:33",
			guestName: "James O'Connor",
			listingName: "Historic Townhouse - Old Quarter",
		},
		{
			id: 1011,
			type: "host-to-guest",
			status: "published",
			rating: null,
			publicReview:
				"James was respectful and communicative. Welcome back anytime!",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "respect_house_rules", rating: 10 },
			],
			submittedAt: "2024-09-09 08:45:12",
			guestName: "James O'Connor",
			listingName: "Historic Townhouse - Old Quarter",
		},
		{
			id: 1012,
			type: "guest-to-host",
			status: "published",
			rating: 8,
			publicReview:
				"Great location near the metro. Apartment was comfortable and had everything we needed.",
			reviewCategory: [
				{ category: "cleanliness", rating: 8 },
				{ category: "communication", rating: 9 },
				{ category: "check-in", rating: 8 },
				{ category: "accuracy", rating: 8 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-10-08 15:25:41",
			guestName: "Nina Kozlov",
			listingName: "Metro View Apartment - Transport Hub",
		},
		{
			id: 1013,
			type: "guest-to-host",
			status: "published",
			rating: 4,
			publicReview:
				"Disappointed. Photos didn't match reality. Noisy neighbors and poor maintenance.",
			reviewCategory: [
				{ category: "cleanliness", rating: 5 },
				{ category: "communication", rating: 6 },
				{ category: "check-in", rating: 5 },
				{ category: "accuracy", rating: 3 },
				{ category: "location", rating: 6 },
			],
			submittedAt: "2024-09-19 21:30:15",
			guestName: "Tom Mitchell",
			listingName: "Budget Studio - University Area",
		},
		{
			id: 1014,
			type: "guest-to-host",
			status: "published",
			rating: 9,
			publicReview:
				"Beautiful space with amazing views! Host was very accommodating with our late check-in.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 9 },
				{ category: "check-in", rating: 10 },
				{ category: "accuracy", rating: 9 },
				{ category: "location", rating: 9 },
			],
			submittedAt: "2024-09-30 10:15:28",
			guestName: "Maria Santos",
			listingName: "Mountain View Chalet - Alpine Heights",
		},
		{
			id: 1015,
			type: "host-to-guest",
			status: "published",
			rating: null,
			publicReview:
				"Maria and her family were excellent guests. Highly recommended!",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 9 },
				{ category: "respect_house_rules", rating: 10 },
			],
			submittedAt: "2024-10-01 09:20:33",
			guestName: "Maria Santos",
			listingName: "Mountain View Chalet - Alpine Heights",
		},
		{
			id: 1016,
			type: "guest-to-host",
			status: "awaiting",
			rating: null,
			publicReview: null,
			reviewCategory: [],
			submittedAt: "2024-10-14 08:00:00",
			guestName: "Kevin Park",
			listingName: "Lakeside Cottage - Waterfront",
		},
		{
			id: 1017,
			type: "guest-to-host",
			status: "published",
			rating: 7,
			publicReview:
				"Solid option for the price. Nothing fancy but met our basic needs.",
			reviewCategory: [
				{ category: "cleanliness", rating: 7 },
				{ category: "communication", rating: 7 },
				{ category: "check-in", rating: 7 },
				{ category: "accuracy", rating: 7 },
				{ category: "location", rating: 6 },
			],
			submittedAt: "2024-09-25 17:45:22",
			guestName: "Rachel Green",
			listingName: "Simple Stay - Suburban Comfort",
		},
		{
			id: 1018,
			type: "guest-to-host",
			status: "published",
			rating: 10,
			publicReview:
				"Incredible stay! The kitchen was fully equipped and perfect for cooking. Will definitely return!",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 10 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 9 },
			],
			submittedAt: "2024-10-06 14:35:50",
			guestName: "Ahmed Hassan",
			listingName: "Chef's Paradise - Gourmet Kitchen",
		},
		{
			id: 1019,
			type: "guest-to-host",
			status: "published",
			rating: 8,
			publicReview:
				"Very nice apartment. Walking distance to everything. Only issue was parking.",
			reviewCategory: [
				{ category: "cleanliness", rating: 9 },
				{ category: "communication", rating: 8 },
				{ category: "check-in", rating: 7 },
				{ category: "accuracy", rating: 8 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-09-12 11:50:44",
			guestName: "Olivia Brown",
			listingName: "Walkable Wonder - City Heart",
		},
		{
			id: 1020,
			type: "host-to-guest",
			status: "pending",
			rating: null,
			publicReview: null,
			reviewCategory: [],
			submittedAt: "2024-10-13 15:30:00",
			guestName: "Olivia Brown",
			listingName: "Walkable Wonder - City Heart",
		},
		{
			id: 1021,
			type: "guest-to-host",
			status: "published",
			rating: 9,
			publicReview:
				"Fantastic for remote work! Fast WiFi and comfortable workspace. Host thought of everything.",
			reviewCategory: [
				{ category: "cleanliness", rating: 9 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 9 },
				{ category: "accuracy", rating: 9 },
				{ category: "location", rating: 8 },
			],
			submittedAt: "2024-09-05 13:20:11",
			guestName: "Yuki Tanaka",
			listingName: "Digital Nomad Hub - Co-working Space",
		},
		{
			id: 1022,
			type: "guest-to-host",
			status: "published",
			rating: 6,
			publicReview:
				"Average experience. The bed was uncomfortable and AC wasn't working properly.",
			reviewCategory: [
				{ category: "cleanliness", rating: 6 },
				{ category: "communication", rating: 7 },
				{ category: "check-in", rating: 7 },
				{ category: "accuracy", rating: 5 },
				{ category: "location", rating: 7 },
			],
			submittedAt: "2024-10-09 19:10:37",
			guestName: "Carlos Mendes",
			listingName: "Economy Suite - Budget Friendly",
		},
		{
			id: 1023,
			type: "guest-to-host",
			status: "published",
			rating: 10,
			publicReview:
				"Best place we've ever stayed! Luxury finishes, incredible host, and perfect location. Worth every penny!",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 10 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-09-18 12:05:29",
			guestName: "Isabella Ferrari",
			listingName: "Presidential Suite - Luxury Tower",
		},
		{
			id: 1024,
			type: "host-to-guest",
			status: "published",
			rating: null,
			publicReview:
				"Isabella was a perfect guest! Very respectful and easy to communicate with.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "respect_house_rules", rating: 10 },
			],
			submittedAt: "2024-09-19 09:30:15",
			guestName: "Isabella Ferrari",
			listingName: "Presidential Suite - Luxury Tower",
		},
		{
			id: 1025,
			type: "guest-to-host",
			status: "expired",
			rating: null,
			publicReview: null,
			reviewCategory: [],
			submittedAt: "2024-08-20 23:59:59",
			guestName: "Michael Zhang",
			listingName: "Corner Apartment - Shopping District",
		},
		{
			id: 1026,
			type: "guest-to-host",
			status: "published",
			rating: 8,
			publicReview:
				"Charming place with character. Loved the vintage decor and cozy atmosphere.",
			reviewCategory: [
				{ category: "cleanliness", rating: 8 },
				{ category: "communication", rating: 9 },
				{ category: "check-in", rating: 8 },
				{ category: "accuracy", rating: 9 },
				{ category: "location", rating: 7 },
			],
			submittedAt: "2024-08-28 16:40:22",
			guestName: "Hannah Baker",
			listingName: "Vintage Loft - Creative District",
		},
		{
			id: 1027,
			type: "guest-to-host",
			status: "published",
			rating: 9,
			publicReview:
				"Perfect for a romantic getaway! The balcony view at sunset was breathtaking.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 9 },
				{ category: "check-in", rating: 9 },
				{ category: "accuracy", rating: 9 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-09-03 14:15:44",
			guestName: "Pierre Dubois",
			listingName: "Romantic Retreat - Hilltop View",
		},
		{
			id: 1028,
			type: "host-to-guest",
			status: "published",
			rating: null,
			publicReview:
				"Pierre was a delightful guest. Very tidy and respectful of our space.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 9 },
				{ category: "respect_house_rules", rating: 10 },
			],
			submittedAt: "2024-09-04 10:25:18",
			guestName: "Pierre Dubois",
			listingName: "Romantic Retreat - Hilltop View",
		},
		{
			id: 1029,
			type: "guest-to-host",
			status: "published",
			rating: 5,
			publicReview:
				"Not as advertised. The photos must be old - furniture is worn and outdated.",
			reviewCategory: [
				{ category: "cleanliness", rating: 6 },
				{ category: "communication", rating: 5 },
				{ category: "check-in", rating: 6 },
				{ category: "accuracy", rating: 3 },
				{ category: "location", rating: 7 },
			],
			submittedAt: "2024-08-15 20:35:11",
			guestName: "Jennifer Lee",
			listingName: "Classic Apartment - Heritage Building",
		},
		{
			id: 1030,
			type: "guest-to-host",
			status: "published",
			rating: 10,
			publicReview:
				"Five stars aren't enough! Impeccably clean, stunning design, and host went above and beyond.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 10 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-09-11 11:20:33",
			guestName: "Sebastian Mueller",
			listingName: "Designer Penthouse - Fashion District",
		},
		{
			id: 1031,
			type: "guest-to-host",
			status: "published",
			rating: 7,
			publicReview:
				"Decent stay overall. Good for the price but nothing exceptional.",
			reviewCategory: [
				{ category: "cleanliness", rating: 7 },
				{ category: "communication", rating: 7 },
				{ category: "check-in", rating: 7 },
				{ category: "accuracy", rating: 7 },
				{ category: "location", rating: 8 },
			],
			submittedAt: "2024-08-22 13:50:27",
			guestName: "Priya Sharma",
			listingName: "Standard Suite - Commercial Zone",
		},
		{
			id: 1032,
			type: "guest-to-host",
			status: "published",
			rating: 9,
			publicReview:
				"Great for families! The kids loved the game room and the backyard was perfect for them to play.",
			reviewCategory: [
				{ category: "cleanliness", rating: 9 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 9 },
				{ category: "accuracy", rating: 9 },
				{ category: "location", rating: 8 },
			],
			submittedAt: "2024-09-07 15:45:12",
			guestName: "Thomas Wright",
			listingName: "Family Haven - Suburban Retreat",
		},
		{
			id: 1033,
			type: "host-to-guest",
			status: "published",
			rating: null,
			publicReview:
				"Thomas and family were wonderful! Left everything in perfect condition.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "respect_house_rules", rating: 10 },
			],
			submittedAt: "2024-09-08 09:10:55",
			guestName: "Thomas Wright",
			listingName: "Family Haven - Suburban Retreat",
		},
		{
			id: 1034,
			type: "guest-to-host",
			status: "published",
			rating: 6,
			publicReview:
				"Okay place but had some issues. Water pressure was weak and heater didn't work well.",
			reviewCategory: [
				{ category: "cleanliness", rating: 7 },
				{ category: "communication", rating: 6 },
				{ category: "check-in", rating: 7 },
				{ category: "accuracy", rating: 5 },
				{ category: "location", rating: 7 },
			],
			submittedAt: "2024-08-25 18:22:40",
			guestName: "Anna Kowalski",
			listingName: "Cozy Studio - Arts District",
		},
		{
			id: 1035,
			type: "guest-to-host",
			status: "scheduled",
			rating: null,
			publicReview: null,
			reviewCategory: [],
			submittedAt: "2024-10-16 12:00:00",
			guestName: "Mohammed Ali",
			listingName: "Skyline Penthouse - Downtown Luxury",
		},
		{
			id: 1036,
			type: "guest-to-host",
			status: "published",
			rating: 8,
			publicReview:
				"Really enjoyed our stay. The neighborhood was quiet and safe. Host was helpful with recommendations.",
			reviewCategory: [
				{ category: "cleanliness", rating: 8 },
				{ category: "communication", rating: 9 },
				{ category: "check-in", rating: 8 },
				{ category: "accuracy", rating: 8 },
				{ category: "location", rating: 9 },
			],
			submittedAt: "2024-09-14 10:30:19",
			guestName: "Grace Kim",
			listingName: "Peaceful Oasis - Quiet Neighborhood",
		},
		{
			id: 1037,
			type: "guest-to-host",
			status: "published",
			rating: 10,
			publicReview:
				"Exceeded all expectations! Modern, clean, and the smart home features were amazing.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 10 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 9 },
			],
			submittedAt: "2024-08-30 12:55:44",
			guestName: "Lucas Silva",
			listingName: "Smart Home - Tech Haven",
		},
		{
			id: 1038,
			type: "host-to-guest",
			status: "published",
			rating: null,
			publicReview:
				"Lucas was an exemplary guest. Great communication throughout!",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "respect_house_rules", rating: 10 },
			],
			submittedAt: "2024-08-31 08:40:22",
			guestName: "Lucas Silva",
			listingName: "Smart Home - Tech Haven",
		},
		{
			id: 1039,
			type: "guest-to-host",
			status: "published",
			rating: 4,
			publicReview:
				"Very disappointed. Lots of street noise kept us awake. Not worth the price.",
			reviewCategory: [
				{ category: "cleanliness", rating: 6 },
				{ category: "communication", rating: 5 },
				{ category: "check-in", rating: 5 },
				{ category: "accuracy", rating: 3 },
				{ category: "location", rating: 4 },
			],
			submittedAt: "2024-09-20 22:10:33",
			guestName: "Emily Davis",
			listingName: "City Center Flat - Business District",
		},
		{
			id: 1040,
			type: "guest-to-host",
			status: "published",
			rating: 9,
			publicReview:
				"Wonderful artistic space! Loved the gallery wall and creative vibe. Perfect for our anniversary.",
			reviewCategory: [
				{ category: "cleanliness", rating: 9 },
				{ category: "communication", rating: 9 },
				{ category: "check-in", rating: 9 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 8 },
			],
			submittedAt: "2024-09-01 14:25:50",
			guestName: "Fatima Ibrahim",
			listingName: "Artist's Studio - Gallery Quarter",
		},
		{
			id: 1041,
			type: "guest-to-host",
			status: "published",
			rating: 7,
			publicReview:
				"Good location near attractions. Apartment was fine but could use some upgrades.",
			reviewCategory: [
				{ category: "cleanliness", rating: 7 },
				{ category: "communication", rating: 8 },
				{ category: "check-in", rating: 7 },
				{ category: "accuracy", rating: 7 },
				{ category: "location", rating: 9 },
			],
			submittedAt: "2024-08-18 17:15:26",
			guestName: "Daniel Foster",
			listingName: "Tourist Central - Landmark Area",
		},
		{
			id: 1042,
			type: "guest-to-host",
			status: "published",
			rating: 10,
			publicReview:
				"Absolutely pristine! The attention to cleanliness was remarkable. Felt like a luxury hotel.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 10 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-09-26 11:05:17",
			guestName: "Chloe Martin",
			listingName: "Presidential Suite - Luxury Tower",
		},
		{
			id: 1043,
			type: "host-to-guest",
			status: "published",
			rating: null,
			publicReview: "Chloe was amazing! Treated our home with utmost respect.",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "respect_house_rules", rating: 10 },
			],
			submittedAt: "2024-09-27 09:15:44",
			guestName: "Chloe Martin",
			listingName: "Presidential Suite - Luxury Tower",
		},
		{
			id: 1044,
			type: "guest-to-host",
			status: "published",
			rating: 8,
			publicReview:
				"Great base for exploring the city. Public transport nearby made everything accessible.",
			reviewCategory: [
				{ category: "cleanliness", rating: 8 },
				{ category: "communication", rating: 8 },
				{ category: "check-in", rating: 9 },
				{ category: "accuracy", rating: 8 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-08-12 13:40:55",
			guestName: "Liam Murphy",
			listingName: "Metro View Apartment - Transport Hub",
		},
		{
			id: 1045,
			type: "guest-to-host",
			status: "awaiting",
			rating: null,
			publicReview: null,
			reviewCategory: [],
			submittedAt: "2024-10-15 07:30:00",
			guestName: "Zara Ahmed",
			listingName: "Garden View Suite - Riverside",
		},
		{
			id: 1046,
			type: "guest-to-host",
			status: "published",
			rating: 6,
			publicReview:
				"Mixed feelings. Location was great but apartment needs maintenance. Shower leaked.",
			reviewCategory: [
				{ category: "cleanliness", rating: 6 },
				{ category: "communication", rating: 7 },
				{ category: "check-in", rating: 7 },
				{ category: "accuracy", rating: 5 },
				{ category: "location", rating: 9 },
			],
			submittedAt: "2024-09-17 19:50:12",
			guestName: "Ryan Cooper",
			listingName: "Walkable Wonder - City Heart",
		},
		{
			id: 1047,
			type: "guest-to-host",
			status: "published",
			rating: 9,
			publicReview:
				"Stunning views from every window! Host provided welcome basket which was a nice touch.",
			reviewCategory: [
				{ category: "cleanliness", rating: 9 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 9 },
				{ category: "accuracy", rating: 9 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-08-08 15:20:38",
			guestName: "Valentina Rossi",
			listingName: "Sunset View Apartment - Marina Bay",
		},
		{
			id: 1048,
			type: "host-to-guest",
			status: "submitted",
			rating: null,
			publicReview: "Valentina was a pleasure to host. Would welcome her back!",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "respect_house_rules", rating: 9 },
			],
			submittedAt: "2024-08-09 10:45:23",
			guestName: "Valentina Rossi",
			listingName: "Sunset View Apartment - Marina Bay",
		},
		{
			id: 1049,
			type: "guest-to-host",
			status: "published",
			rating: 5,
			publicReview:
				"Below average. WiFi kept dropping and there were issues with hot water.",
			reviewCategory: [
				{ category: "cleanliness", rating: 6 },
				{ category: "communication", rating: 5 },
				{ category: "check-in", rating: 6 },
				{ category: "accuracy", rating: 4 },
				{ category: "location", rating: 6 },
			],
			submittedAt: "2024-09-23 21:25:47",
			guestName: "Benjamin Scott",
			listingName: "Digital Nomad Hub - Co-working Space",
		},
		{
			id: 1050,
			type: "guest-to-host",
			status: "published",
			rating: 10,
			publicReview:
				"Perfect in every way! This is our new go-to place when visiting the city. Highly recommend!",
			reviewCategory: [
				{ category: "cleanliness", rating: 10 },
				{ category: "communication", rating: 10 },
				{ category: "check-in", rating: 10 },
				{ category: "accuracy", rating: 10 },
				{ category: "location", rating: 10 },
			],
			submittedAt: "2024-10-04 12:35:29",
			guestName: "Sophie Andersen",
			listingName: "Historic Townhouse - Old Quarter",
		},
	],
	count: 50,
	offset: 0,
};
